version: '3.8'

services:
  book_catalog:
    image: book-catalog:1
    build:
      context: ./book_catalog
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}

  inventory_management:
    image: inventory-management:1
    build:
      context: ./inventory_management
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}