version: '3.8'

services:
  book_catalog:
    image: book-catalog:1
    build:
      context: ./book_catalog
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://deakin_library_722_user:UlunAR56RZfjyTK0G873zz4uJ5ggnrDp@dpg-crimtk3v2p9s738krkog-a.oregon-postgres.render.com/deakin_library_722

  inventory_management:
    image: inventory-management:1
    build:
      context: ./inventory_management
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://deakin_library_722_user:UlunAR56RZfjyTK0G873zz4uJ5ggnrDp@dpg-crimtk3v2p9s738krkog-a.oregon-postgres.render.com/deakin_library_722