version: '3.8'

services:
  book_catalog:
    image: book-catalog:1
    build:
      context: ./book_catalog
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://deakin_libray_user:JlVIo0PD52bS3x5D0f45tq4mhAsR53XN@dpg-crn961e8ii6s73empe6g-a.oregon-postgres.render.com/deakin_libray

  inventory_management:
    image: inventory-management:1
    build:
      context: ./inventory_management
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://deakin_libray_user:JlVIo0PD52bS3x5D0f45tq4mhAsR53XN@dpg-crn961e8ii6s73empe6g-a.oregon-postgres.render.com/deakin_libray