apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-deployment
  labels:
    app: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
        - name: inventory-management
          image: deakinlibrary.azurecr.io/inventory-management-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: library-secrets
                  key: DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  selector:
    app: inventory-management
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8000
  type: LoadBalancer