name: Destroy Infrastructure

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Azure using the credentials
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=deakinlibrary" \
            -backend-config="storage_account_name=terraformstatedaosgava" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=terraform.tfstate"
        working-directory: ./infrastructure

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false -lock-timeout=5m
        working-directory: ./infrastructure
