name: Deploy Infrastructure

on:
  #
  # Deploy the microservice on push to any branch of this code repository.
  #
  push: 
    branches:
      - main
    paths:
      - ./infrastructure/**

  #
  # Allows deployment to be invoked manually through the GitHub Actions user interface.
  #
  workflow_dispatch: 

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5

      - name: Login to Azure
        uses: Azure/login@v1
        with:
          creds: '{"clientId": "${{ secrets.AZURE_CLIENT_ID }}", "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}", "tenantId": "${{ secrets.AZURE_TENANT_ID }}", "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"}'


      - name: Terraform Init
        run: terraform init
        working-directory: ./infrastructure

      - name: Import Existing Resource Group
        run: terraform import azurerm_resource_group.deakin_library /subscriptions/382d76a3-f693-49a1-9777-fe5329168fe1/resourceGroups/deakinlibrary
        continue-on-error: true
        working-directory: ./infrastructure

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./infrastructure

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./infrastructure
